apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: thinkpixelag
spec:
  selector:
    matchLabels: {app.kubernetes.io/name: thinkpixelag}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
